### PR TITLE
Updated usage of ERB constructor

### LINKED ISSUE #8: Using in ruby 3+ causes warnings about ERB.new
When using simplecov-erb in Ruby >3.0, the following warnings are created:
```
Coverage report generated for RSpec to /Users/jar349/src/github/workday-chatops/coverage. 340 / 369 LOC (92.14%) covered.
/Users/jar349/src/github/workday-chatops/vendor/gems/ruby/3.1.0/gems/simplecov-erb-1.0.0/lib/simplecov-erb.rb:53: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/Users/jar349/src/github/workday-chatops/vendor/gems/ruby/3.1.0/gems/simplecov-erb-1.0.0/lib/simplecov-erb.rb:53: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
Coverage report generated for RSpec to /Users/jar349/src/github/workday-chatops/coverage/coverage.txt. 340 / 369 LOC (92.14%) covered.
--------------------------------------------------------------------------------
Incomplete test coverage
--------------------------------------------------------------------------------

/lib/commands/for.rb: 92.41% (missed: 158,193,197,198,199,201)
/lib/models/job_completion_handler.rb: 30.3% (missed: 12,13,14,18,19,21,23,25,28,31,32,37,38,40,42,44,49,50,51,55,59,66,68)
```

I'm sorry for the horizontal scrolling; I wanted to keep the output verbatim.

### PR DESCRIPTION
**Pull request by jar349**
Closes #8

I was wrong about the culprit being ruby 3.0. What really happened was that we updated all our dependencies to latest and that brought a newer simplecov, which had deprecated some of its constructor's method parameters.

This PR updates simplecov-erb to conform to the ERB constructor's new desired method signature. It then bumps the version of the gem to `1.0.1` and it makes some very slight changes to the gemspec so that running `gem build` will not give any warnings. Specifically, that meant:
- dropping the description since it was just exactly equal to the summary.
- setting the required version of simplecov to `< 1.0` because otherwise it was unbounded
- setting the license to `MIT` since this matches what you have in `LICENSE`

### CODE REVIEW

**Comment by kpaulisse** [comment]
Hey @jar349 , good to hear from you and I hope things are going well.

It looks like this syntax changed between Ruby 2.5 and Ruby 2.6. With an acknowledgement that Ruby 2.5 is EOL, to maintain backward compatibility for anyone who is still using it, could you update this to use the new syntax `if RUBY_VERSION >= "2.6"` or else use the old syntax?

I'll be happy to accept your PR with that change made. Thanks in advance.

**Comment by jar349** [comment]
@kpaulisse Telling you that you are much missed over text hurts me because it cannot possibly convey the magnitude of how true it is. 

I believe that using `Gem::Version` is a better choice for comparing version strings because otherwise the comparison is lexicographical, i.e. `"2.6.6 >= 2.10.0" => true`.

In order to unblock us, I built and vendored a gem from my fork, which caused this PR to fall out of my mind. I apologize for how long it took me to perform this simple task.

**Comment by jar349** [comment]
@kpaulisse I'm sorry for how long it took me to make your requested changes. At this point is there more I can do before you are ready to run the tests?

**Comment by rick** [comment]
oh hai

You'll never guess who was poking around upgrading things and ended up right here. OK, you will.  Stoked for a merge if it's legit.

**Review by kpaulisse — APPROVED** [review]
:scream_cat: Sorry I missed the earlier ping - I've just become *that guy*.

Thanks for the contribution. Approving and merging.

**Comment by kpaulisse** [comment]
@jar349 @rick Could you push a dummy commit or whatever's needed to run the tests?

**Comment by jar349** [comment]
@kpaulisse you may need to approve again since I've pushed?

**Comment by jar349** [comment]
Screen Shot 2022-09-01 at 5 07 57 PM

**Comment by kpaulisse** [comment]
Approved your run since it doesn't appear you're mining bitcoin or anything :joy_cat:

**Comment by kpaulisse** [comment]
Oh no! Trailing whitespace! :crying_cat_face:

**Comment by jar349** [comment]
I must have done something stupid with my dummy commit because I swear I ran `./script/cibuild` before cutting the PR.  At any rate... as is tradition... here's the "appease the linter" commit. 😂

**Comment by jar349** [comment]
do you want me to drop the unintentional changes to the gemfile.lock? Apparently, the bootstrap script updated that when I ran `cibuild`

**Comment by kpaulisse** [comment]
Sure, probably keep the version number but maybe drop the bundler version and platforms. I'm not sure who all uses this, but the fewer changes the better probably...

**Comment by kpaulisse** [comment]
https://rubygems.org/gems/simplecov-erb/versions/1.0.1

Feel free to yell louder at me next time if I miss your additional commits - sorry about the delay and thanks again for contributing!

**Comment by rick** [comment]
noice

Sweet! Thanks!

**Pull request merged**
